spring:
  application:
    name: api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unishare_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Hop2005@}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080